name: main
on:
  push:
    branches:
      - 'master'
  pull_request:
jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    name: Build and test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          # Action runs: using: node20 as defined in
          # https://github.com/cypress-io/github-action/blob/master/action.yml
          # Node.js minor version is aligned to
          # https://github.com/actions/runner/blob/main/src/Misc/externals.sh
          node-version: 18.17.0
      - run: npm ci
      - run: npm run format
      - run: npm run build
      - run: npm test
      - name: Install dependencies
        run: npm install

