name: main
on:
  push:
    branches:
      - 'master'
  pull_request:
jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    name: Build and test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm install
      - name: Run Cypress Tests
        run: npm run cypress:run

